# Streamlit Secrets Configuration
# Copy your BigQuery service account credentials here
# This should be the SAME credentials you use for your retail sales app

[gcp_service_account]
type = "service_account"
project_id = "moonlit-autumn-468306-p6"
private_key_id = "783a4505ed2c8f63fe6048194ad4eea580f361d8"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDViX1ttbesmHSa\nWruCaSDFL9FW5OATN/d1rxdZaGmbM4y3TnlYYGJbT9rbGvwHgFLly5lC8613UOgw\nDh1HDqZe5Hm4EjvRYz3BwduCux8Q9+jQpQNS2WGKncrttYLxhFZjcj/1kManfYUJ\nwb4GpDRLDg+OWTx3IpfH9q9JzYimcPGzijM1C/3TXB5n52LLk70sb058MmPlX3wG\ntqyExoVZz0yvbKSBlkmcyaYvcY5+ciDAJYv3xJWvcbtYXfFmt8caDcQdBbjrhIzQ\nX2lO9dfeuhpa8ZHrsKTGcK7ZIXFXivYPW+sA2HgUFTlGq9muhjkltgI0de9+v9PS\na8sglhuDAgMBAAECggEAKAUJC1crsb6u18DadJH0UNBp6OGjNybdi2JBu4FsjWhH\nXpFn/46s0FUyfK7dfiBoKOYT9q7Jm1t/8IWsqgUOXClwwHU2XcM+L0KAO8uLAnib\n2wKaEVxpQfvZrNxASrhVInUmlITKHljRZqc3UHJU1J4xfymtQdyrWpAagPfyvNKF\nVBcAJ95NMh01MS4iy0dN2e7blnU8UyvuSfUL46hg988KJTD1GaaQF/I+1O7DwgpQ\nzRWj2ghisVcLKRnmoTnQoWCDrhujEl5ju/9gTYOH/w0Ciurv/pH/8AXNc8CT+ERl\nGqVZXyUsNrsDVeWa0xhRTd8cjdpP8KsxIJr3oIM0AQKBgQD1chA2T0Y0GV7Z8XDq\nCcG0PIGXP4OcIVnxcvm1u8gIqAmOsk1Jd2IMVftYprXEqZF7uALInd9HEiHl5hSL\nt7iuuW/IPwvnHFqhpZbeOCmEfCmhzrrHilch7Jo/5ehdX04/3VGAeWHgWtjU93HB\nVCaMvHER0ePYj+w/7SPGYi/kAQKBgQDeuCsqjl6q5uhDFucbIjc5LDDW0Ui/5kga\naiZpBP6ZXrmE1VeVQvc0+yPTLxkA1DgtPZve5swv3etPQiONcuCATisZEKtFLwUb\nu53h7qtHi2/JozmIfxed7NH+k2NE9AJIL+JrL5GePSpMjPwoExwVNESmFOnnbtGK\nFT0CPjhvgwKBgQDKKL+3q8W8BaV9RwLkkVKtPCTUyaiCAWpOl4+bIuaYUqdElBFa\nUG0+kdcq5mzSZYQBbcdFK9sKc6Hd9Iq5pYIEz5GFUoBgQ5dWisffkkyH5ah4sIhg\n783ikDlgJeIkfeo6afTGJ7P5EXqEtqZIQSJbSp6qucC7z5cb9BtCO/8MAQKBgQCN\nUW6SYiPPbRSS/UVHAj7oGBIlPEZc/VFi8VfN601hI6mzj2szWnphM7lXltrWm9HJ\nYv40QV3uQXG9qMnGRs4Mm4zdKqaCD4O+RR247ifgDamw19D5uyrRGiNk1UB30Bxi\nkX+pY1WSgl0ElbCp/PYkvjWQ7FQ+dSKf6zn64mAM4QKBgCjagDO+Vt3/UWvHO7F7\nyLSNSj4uDDGpIF08mPYh05kfoE/w32IhYsw3U+UIuaObomhYpJeCYYLDLbyv/inx\nN5YWSsBq/SoyudFfr3EEZ5bdL1O6/18EFreVwod2InLWfRoWibVg6MVuWlOt7C21\ns3ZkK13lm+6cwAae4YCJFYCX\n-----END PRIVATE KEY-----\n"
client_email = "bulelani-kote@moonlit-autumn-468306-p6.iam.gserviceaccount.com"
client_id = "116228650630636664819"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bulelani-kote%40moonlit-autumn-468306-p6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# INSTRUCTIONS:
# 1. Replace ALL the placeholder values above with your actual BigQuery credentials
# 2. Use the SAME credentials that work with your retail sales app
# 3. Make sure to keep the exact formatting and quotes
# 4. The private_key should include the \n characters for line breaks

